In [1]:
import pandas as pd

df_exams = pd.read_csv(r"D:\python-for-data-science-main\02.Intro to Pandas\StudentsPerformance.csv")
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75


In [2]:
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70


In [3]:
import numpy as np
np.arange(0, 1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [4]:
len(np.arange(0, 1000))

1000

In [5]:
language_score = np.arange(0, 1000)
len(language_score)

1000

In [6]:
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998


In [7]:
int_language_score = np.random.randint(1, 100, size=1000)
int_language_score

array([79, 69,  8, 60, 18, 96, 65, 44, 40, 56, 33, 55, 16, 89, 94,  1, 44,
       82, 43, 23, 80, 67, 30,  4, 74, 52, 29, 81, 96, 17, 61, 98, 52,  7,
        5, 10, 12, 89, 33, 79, 17, 60, 32, 84, 63, 88,  1, 63,  2, 87, 43,
       15, 64, 53, 61,  4,  5, 72, 88, 70, 43, 26, 19, 92, 13, 51, 84, 38,
       74, 46, 77, 84, 91, 88, 25, 26, 89, 17, 40,  7, 59, 60, 95,  2, 32,
       56, 55,  8,  9, 14, 31, 96, 35, 20, 29, 41, 50, 31, 17, 60, 82, 29,
       42, 90, 81, 77, 89, 87, 83, 25,  1, 62, 94, 42, 30, 22,  1, 59, 24,
       35, 78, 53, 63, 71, 68, 26, 45, 26, 66, 76, 77, 84, 48, 54, 98, 21,
       81, 93, 56,  4, 88, 85, 46, 63, 33, 66, 59, 12, 34, 62, 43, 55,  6,
       61, 73, 57, 80, 33, 18, 25, 58, 18, 31, 78, 70, 18, 92, 97, 10,  5,
       39, 59, 58,  3, 75, 95, 82, 24, 59,  7, 38, 57, 20,  3, 38, 43,  6,
       79, 10, 57,  2, 57, 40, 21, 22, 14,  1, 79, 12, 65, 83, 69,  1, 46,
        7, 17, 86, 52, 45, 47, 16, 15, 34, 77, 14, 82,  6, 13, 65, 24, 49,
       72, 83, 59, 83, 23

In [8]:
min(int_language_score)
max(int_language_score)

99

In [11]:
df_exams['language_score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score
0,female,group B,bachelor's degree,standard,none,72,72,74,0,0
1,female,group C,some college,standard,completed,69,90,88,1,1
2,female,group B,master's degree,standard,none,90,95,93,2,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3,3
4,male,group C,some college,standard,none,76,78,75,4,4
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995,995
996,male,group C,high school,free/reduced,none,62,55,55,996,996
997,female,group C,high school,free/reduced,completed,59,71,65,997,997
998,female,group D,some college,standard,completed,68,78,77,998,998


In [13]:
np.random.uniform(1,100, size=100)

array([52.09683782, 62.21272076, 59.2282949 , 81.42018745, 99.23660787,
       60.7710412 , 43.78812854, 80.17979581, 20.36619809, 75.92824481,
       44.09691424, 72.08649975, 41.49150864, 86.66174881, 79.54340281,
       68.0936153 , 62.60577509, 42.87811435, 55.713673  , 94.36414129,
       86.3846012 , 98.38298467, 57.90808374, 61.28597339, 66.91677461,
       36.40486653, 98.79476977, 80.16254053, 35.97436719, 54.31891908,
       79.7363215 , 29.4798336 ,  7.66253959, 84.03184725, 48.95782894,
       74.22820889, 55.79486829,  5.95756929, 37.06072854, 32.28662175,
       35.08620219, 55.95259149, 83.95798658, 68.99825018, 23.18464335,
       52.33853131,  6.47156933, 74.15609822, 23.84891016, 53.01164851,
       47.90084292, 83.57649979, 56.49845138, 13.77781328, 98.7865487 ,
       57.48733353, 44.77992439, 17.58511471, 93.78586197, 11.1532247 ,
        5.32528969, 38.64793346, 38.86847435, 37.11145777, 46.87148024,
       99.44733761, 75.90445357, 55.04271561,  5.12860891, 93.30