In [1]:
import tensorflow as tf  
print(tf.version)  

<module 'tensorflow._api.v2.version' from 'D:\\Anaconda\\envs\\tf\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [2]:
# Creating Tensors

string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64) 

In [3]:
# Rank / Degree of Tensors

rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [4]:
# Determine The Rank of a Tensor

tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
# Shape of Tensors

rank2_tensor.shape

TensorShape([2, 2])

In [6]:
# Changing Shape

tensor1 = tf.ones([1,2,3])  
tensor2 = tf.reshape(tensor1, [2,3,1]) 
tensor3 = tf.reshape(tensor2, [3, -1]) 

In [7]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [8]:
# Slicing Tensor

# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [9]:
three = tensor[0,2]  
print(three)  

row1 = tensor[0]  
print(row1)

column1 = tensor[:, 0]  
print(column1)

row_2_and_4 = tensor[1::2]  
print(row2and4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)


NameError: name 'row2and4' is not defined