In [1]:
pip install gymnasium

Note: you may need to restart the kernel to use updated packages.


In [2]:
import gymnasium as gym
env = gym.make('FrozenLake-v1') 

In [3]:
print(env.observation_space.n)  
print(env.action_space.n)  

16
4


In [4]:
env.reset()

(0, {'prob': 1})

In [5]:
action = env.action_space.sample()

In [6]:
new_state = env.step(action) 

In [7]:
env.render()

D:\Anaconda\envs\tf\lib\site-packages\gymnasium\envs\toy_text\frozen_lake.py:353: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym.make("FrozenLake-v1", render_mode="rgb_array")
  gym.logger.warn(


In [ ]:
# Frozen Lake Environment 

In [8]:
# Building The Q-Table

import gymnasium
import numpy as np
import time

env = gym.make('FrozenLake-v1')
STATES = env.observation_space.n
ACTIONS = env.action_space.n

In [9]:
Q = np.zeros((STATES, ACTIONS))

In [10]:
# Constants

EPISODES = 2000 
MAX_STEPS = 100 

LEARNING_RATE = 0.81  
GAMMA = 0.96

In [11]:
# Picking an Action

epsilon = 0.9  

# code to pick action
if np.random.uniform(0, 1) < epsilon:  
    action = env.action_space.sample()  
else:
    action = np.argmax(Q[state, :]) 

In [12]:
env = gymnasium.make("FrozenLake-v1")

state, info = env.reset()
action = env.action_space.sample()
new_state, reward, terminated, truncated, info = env.step(action)

In [13]:
# Updating Q Values

Q[state, action] = Q[state, action] + LEARNING_RATE * (reward + GAMMA * np.max(Q[new_state, :]) - Q[state, action])

In [14]:
RENDER = False

if RENDER:
    env = gymnasium.make("FrozenLake-v1", render_mode="human")
else:
    env = gymnasium.make("FrozenLake-v1")

In [15]:
rewards = []

for episode in range(EPISODES):

    state, _ = env.reset()

    for _ in range(MAX_STEPS):

        if RENDER:
            env.render()

        if np.random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q[state, :])

        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated

        Q[state, action] = Q[state, action] + LEARNING_RATE * (
            reward + GAMMA * np.max(Q[next_state, :]) - Q[state, action]
        )

        state = next_state

        if done:
            rewards.append(reward)
            epsilon = max(0, epsilon - 0.001)
            break

print(Q)

if len(rewards) > 0:
    print(f"Average reward: {sum(rewards) / len(rewards)}")
else:
    print("Average reward: 0")

[[3.31654591e-01 2.70677764e-02 2.48972822e-02 2.79604436e-02]
 [2.45489776e-03 9.76417424e-03 6.23311040e-03 3.18120942e-01]
 [6.61139019e-03 9.78138506e-03 1.11700987e-02 1.89348553e-01]
 [8.64555338e-03 7.33209212e-03 2.63649554e-03 1.24135378e-01]
 [2.89577082e-01 1.80466909e-02 1.48041287e-02 5.22035627e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.16008394e-06 7.54388279e-06 2.66727090e-01 6.11691865e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.61338057e-03 2.64648533e-03 2.64634878e-03 2.39135738e-01]
 [6.76814855e-03 1.25936075e-01 6.05161789e-03 6.74073172e-03]
 [5.22706047e-01 7.62203369e-04 9.84234903e-04 4.14064764e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.52860779e-02 4.61139108e-03 3.43361516e-01 4.84341061e-02]
 [1.18232901e-01 5.80501505e-01 2.17754090e-01 2.17130073e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000